# Introduction {#sec:introduction}

The summer (July-August) groundfish research vessel survey on the Scotian Shelf and in the Bay of Fundy was started in 1970 by Fisheries and Oceans Canada Maritimes Region. The survey was originally designed to measure the distribution and abundance of major commercial fish species. Over time, information on non-commercial species was also collected. The groundfish survey database has also been used to produce species status reports and atlases of species distribution. 
This is an update of an earlier reproducible report [@Ricard:MARatlas:2013] that built on former atlases by updating a comprehensive suite of derived indices of 104 species to assess population status and environmental preferences. The R statistical code (R Core Team, 2013) is archived at Fisheries and Oceans Maritimes Region and in a GitHub repository to extract, update and reproduce results. The survey results are stored in a relational database management system which contains detailed information about the sampling locations and the associated catch. Tow-level survey data is also publicly available from the Ocean Biogeographic Information System (OBIS, UNESCO/IOC (2012)). The present atlas follows on the work done by Fisheries and Oceans colleagues from the northern Gulf of St. Lawrence  @Bourdages:NGatlas:2012], southern Gulf of St. Lawrence [@Benoit:etal:2003:techreport] and on earlier work in the Scotian Shelf [@Simon:Comeau:1994; @Horsman:atlas:2009].

The survey area covers three major Northwest Atlantic Fisheries Organization (NAFO) zones that divide the shelf into the colder east 4V and 4W (strata 440-466) and warmer west 4X (strata 470-495). Temporal trends are plotted by NAFO regions for several species. For each species, trends in geographic distribution and biomass or abundance are plotted. Some caution is required in interpreting the results obtained for several taxa due to low sample size as explained later in the text. The spatial extent of distribution is plotted over time to gauge how the area occupied has changed. The relationship between biomass and spatial extent reflects whether the species distribution expands when biomass increases. For each strata, the slope describing how local density varies with regional abundance was estimated (Myers and Stokes, 1989). These slopes were then plotted against a habitat suitability index to identified each species important strata. Then, length frequencies over time depicted any changes in mean size. The plots of condition over time revealed whether individual fish are fatter or thinner than their long term mean. Finally, depth, temperature and salinity preferences were estimated to gauge the range of environmental parameters (Perry and Smith, 1994). A full ecological interpretation of trends is beyond the scope of this report. Further descriptions of spatio-temporal trends in diﬀerent indicators are reported in more detail for common species in Clark and Emberley (2011). Nonetheless, robust widespread populations that tolerate a wide range of environmental parameters are likely to withstand climate change better than depleted, narrowly distributed ones. 

Mapping the distribution of species is critical for the implementation of spatial management and as a first step in Marine Spatial Planning (MSP). MSP is a process aiming at balancing the compatibility of multiple activities and to minimize impacts on the marine ecosystem (Ehler and Douvere 2009). Mapping species distribution can help to identify important sites for a given species or areas of high richness and diversity, which in turn can be used to inform siting decisions of new activities such as Marine Protected Areas (MPA), aquaculture sites or wind turbines. In the Scotian Shelf bioregion, mapping species distributions has been used to highlight areas of high biological diversity to support the identification of Ecologically or Biologically Significant Areas (EBSAs) (Ward-Paige and Bundy 2016), to distinguish important and persistent habitat of significant species and functional groups to support MPA and conservation planning (Horsman et al. 2011, Smith et al. 2015, Bundy et al. 2017, Serdynska et al. In press), to identify important habitat for Species at Risk (SAR) (Harris et al. 2018) and to highlight reserves for data-poor invertebrate fisheries (Shackell et al. 2009). Mapping species distribution has also been used to illustrate multi-decadal scale projections of changes in species distribution in the context of climate change and adaption (Stanley et al. 2018, Greenan et al. 2019). 

This atlas is used as a starting point to examine a species response to climate change in general, and to warming in particular. In support of MSP, a public web-based atlas with relevant geospatial information is being developed to support decision-making. This technical report developed spatial indices of key fish and invertebrate species that may be used in the MSP atlas.



